// Generated by Wrangler by running `wrangler types`

interface Env {
  IMAGE_GENERATION_MODEL: "@cf/stabilityai/stable-diffusion-xl-base-1.0";
  DISCORD_WEBHOOK_ID: string;
  DISCORD_WEBHOOK_TOKEN: string;
  AI: Ai;
}
