#:schema node_modules/wrangler/config-schema.json
name = "team-trivia-scraper"
main = "src/index.ts"
compatibility_date = "2024-10-04"
workers_dev = false
preview_urls = false

[triggers]
crons = ["0 20 * * SUN,WED"] # 1pm MST, 2pm MDT

[vars]
IMAGE_GENERATION_MODEL = "@cf/black-forest-labs/flux-1-schnell"
TEAM_TRIVIA_REGION_ID = "19"
BOT_MESSAGE = "<@&750053568744259664> Trivia tonight! Woody’s Pizza at 9PM; react with <:friedrobert:1013539084792238081> if you’re coming!"

[ai]
binding = "AI"

[observability]
enabled = true
