// This is how workerd imports WebAssembly.
// We need to define each individually instead of defining a *.wasm,
// because otherwise the declaration files generated by wasm-bindgen
// (which are for the ESM imports proposal, not workerd)
// will override the ambient declaration here

declare module "@jsquash/jpeg/codec/enc/mozjpeg_enc.wasm" {
  const mod: WebAssembly.Module;
  export default mod;
}

declare module "@jsquash/png/codec/pkg/squoosh_png_bg.wasm" {
  const mod: WebAssembly.Module;
  export default mod;
}

// We need an ImageData definition to satisfy jSquash
// It's available in workerd, just not listed in the type definitions :/
// and we never manually construct one so its shape doesn't matter
type ImageData = unknown;
